### ISSUE TITLE
Turn this into web app

### ISSUE THREAD

**Issue by lstagner** [matplotlib/viscm#2]
It has probably been suggested I think this would be a great web app where people can create colormaps and submit them to a gallery for voting.

**Comment by njsmith** [comment]
Thanks for the suggestion! Since it would require basically reimplementing everything from scratch in JavaScript, I don't think we're likely to do anything like that soon. It would be cool if someone else feels inspired to do that, though, I agree.

**Comment by tacaswell** [comment]
You could probably get most of the way there with `webagg` which will host a figure on top of a tornado server.

**Comment by njsmith** [comment]
I don't think you're going to get a very satisfying experience of dragging
points around on the screen if you have to do a round trip between every
frame? And also it's turned into a qt app in the mean time... :-)

**Comment by tacaswell** [comment]
oh, I missed the move to real widgets :sheep: 

I have live-demoed viscm in notebooks in talks, worked decently.
