### ISSUE TITLE
Failure to edit diverging colormaps: 'PyQt5.QtWidgets' has no attribute 'QFontMetrics' 

### ISSUE THREAD

**Issue by pierre-haessig** [matplotlib/viscm#23]
Thanks for implementing diverging colormaps (#4). I wanted to test it (using current master) and this is what `python -m viscm -t diverging edit` gives me. Maybe an issue with Qt API version?

```
Traceback (most recent call last):
  File "/home/pierre/Programmes/anaconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pierre/Programmes/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pierre/Programmes/anaconda3/lib/python3.5/site-packages/viscm/__main__.py", line 8, in <module>
    main(sys.argv[1:])
  File "/home/pierre/Programmes/anaconda3/lib/python3.5/site-packages/viscm/gui.py", line 1029, in main
    mainwindow = EditorWindow(figureCanvas, v)
  File "/home/pierre/Programmes/anaconda3/lib/python3.5/site-packages/viscm/gui.py", line 1192, in __init__
    metrics = QtWidgets.QFontMetrics(smoothness_slider_num.font())
AttributeError: module 'PyQt5.QtWidgets' has no attribute 'QFontMetrics'
```

(also I tested `python -m viscm -t diverging-continuous edit` which works, but I don't see a diverging luminance. Maybe the definition of `diverging-continuous` should be clarified.)

**Comment by njsmith** [comment]
Meh, yes, sounds like a qt version issue, thanks for the report.
.
And diverging-continuous is that way on purpose yes, see Peter Kovesi's
colormaps paper for why this is a useful thing. (Basically: it acts like a
diverging map, but with better contrast/discriminibility at the center.)
.
Note that the current master's save format is unstable, so you may lose any
colormaps you make for now.

**Comment by pierre-haessig** [comment]
Excellent article! It may be added as a reference in the README.

Now in terms of terminology, the article uses linear-divergent and divergent-linear, viscm uses diverging-continuous... This is not easy to follow! (adding to the confusion, I would also suggest "diverging-monotonic" as a replacement for "continuous" which is quite ambiguous, or keeping "diverging-linear").

Also, I'm really convinced by Kovesi's explanation about the low discriminibility at the center. Maybe this blue-gray-yellow map, or a close variation, could enter Matplotlib default library?

**Comment by akhmerov** [comment]
Here's a workaround FWIW
```patch
---
 viscm/gui.py | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/viscm/gui.py b/viscm/gui.py
index edefdfe..a6d2dcf 100644
--- a/viscm/gui.py
+++ b/viscm/gui.py
@@ -1189,7 +1189,11 @@ class EditorWindow(QtWidgets.QMainWindow):
 
             # maximum width
             smoothness_slider_num = QtWidgets.QLabel("1000.00")
-            metrics = QtWidgets.QFontMetrics(smoothness_slider_num.font())
+            try:
+                QFontMetrics = QtWidgets.QFontMetrics
+            except AttributeError:
+                from PyQt5.QtGui import QFontMetrics
+            metrics = QFontMetrics(smoothness_slider_num.font())
             max_width = metrics.width("1000.00")
             smoothness_slider_num.setFixedWidth(max_width)
             smoothness_slider_num.setAlignment(QtCore.Qt.AlignRight)
-- 
```

**Comment by tacaswell** [comment]
Can you report this against matplotlib core?  It looks like viscm is using the core qt shims.

**Comment by tacaswell** [comment]
Actually, I think it should always do importing from QtGui.  That it works from `QtWidgets` in pyqt4 is an artifact of how mpl shims over the differences betweer qt4 and qt5 where many things moved from QtGui to the now QtWidgets (by essentially doing `QtWidegts = QtGui`).

See http://doc.qt.io/qt-4.8/qfontmetrics.html and http://doc.qt.io/qt-5.6/qfontmetrics.html

**Comment by stefanv** [comment]
This should be fixed now; please re-open if not.
