### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by akhmerov** [matplotlib/viscm#25]
I observe a possible regression, CPU usage is limiting performance on current master, as compared to a few versions ago. (also with MPL 2 vs 1.5) Perhaps throttling of refresh rate when dragging would be a good idea?

EDIT: also tested on MPL 1.5.3, no difference in performance.

**Comment by stefanv** [comment]
Do you have any more information to help us track this issue down?

**Comment by akhmerov** [comment]
Couldn't reproduce on current master, thanks for pinging me.
