### ISSUE TITLE
Question re: color spacing

### ISSUE THREAD

**Issue by noamross** [matplotlib/viscm#27]
This is question more than an issue.  In generating palettes, does `viscm` select colors that are equally spaced along the brightness axis, and then space points as evenly as possible along the curve in the other dimensions?  Or does it space colors evenly along the curve through color space, so if the colors are desaturated, greys are close but not exactly even?

I'm thinking building a related tool in R, and am thinking about the best approach to space points once a spline is defined in 3D space.

**Comment by njsmith** [comment]
Viscm's colormaps have the property that the distance between points is
exactly analytically uniform both before and after conversion to grey scale.

The way this is accomplished is pretty simple -- we define the lightness
coordinates as a linear ramp, and we select the hue/saturation components
as equally spaced along the 2d line that you draw, and then if you paste
those together to get a curve in 3-space it has the specified property. If
a**2 is constant and b**2 + c**2 is constant then it follows that a**2 +
b**2 + c**2 is also constant.
