### ISSUE TITLE
Version here vs. PyPi

### ISSUE THREAD

**Issue by kthyng** [matplotlib/viscm#3]
I'm getting turned around. It looks like the version here is 0.2 and the version from PyPi is 0.3. Are they out of sync or something? I get the flipped green in the gamut plot with 0.2 but not 0.3

**Comment by njsmith** [comment]
Doh, my bad -- I fixed it and uploaded to PyPI but forgot to push the commit to github.

...but it looks like I don't actually have write access to this repo now that it's moved to the matplotlib organization, so I can't push. Hmm.

**Comment by njsmith** [comment]
Okay, we now have write access to the repo, and I pushed the fix. I'm sorry, that must have been really confusing...

**Comment by kthyng** [comment]
Great, thanks. I was confused there for awhile. I'll try out 0.3!

On Tue, Jul 14, 2015 at 5:41 PM, Nathaniel J. Smith <
notifications@github.com> wrote:

> Okay, we now have write access to the repo, and I pushed the fix. I'm
> sorry, that must have been really confusing...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matplotlib/viscm/issues/3#issuecomment-121414264.

## 

Kristen M. Thyng
Assistant Research Scientist
Department of Oceanography
Texas A&M University
Eller O&M 618
http://kristenthyng.com
