### ISSUE TITLE
GUI Issues

### ISSUE THREAD

**Issue by neilpanchal** [matplotlib/viscm#37]
Just launched `python -m viscm view jet` and I am seeing:

![screen shot 2018-01-16 at 10 22 20 am](https://user-images.githubusercontent.com/8161031/35002556-45b3c1dc-faa7-11e7-9802-6f8549163119.png)

Also, some of the plot controls aren't working (displays blank when adjusting subplot parameters).

**Comment by stefanv** [comment]
I cannot replicate; please re-open if this is still an issue.
