### ISSUE TITLE
example fails on macos: Cannot cast array data from  float64 to uint8

### ISSUE THREAD

**Issue by DSLituiev** [matplotlib/viscm#46]
running `python -m viscm view jet`

```Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 105, in _draw
    self.figure.draw(renderer)
  File "/Applications/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Applications/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/Applications/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Applications/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Applications/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Applications/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Applications/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Applications/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 550, in draw
    renderer.draw_image(gc, l, b, im)
TypeError: Cannot cast array data from dtype('float64') to dtype('uint8') according to the rule 'safe'
```

<details><summary>results of `pip freeze`</summary>
<p>

absl-py==0.2.1
adal==0.6.0
alabaster==0.7.10
anaconda-client==1.6.5
anaconda-project==0.8.0
appdirs==1.4.3
appnope==0.1.0
appscript==1.0.1
asn1crypto==0.22.0
astor==0.6.2
astroid==1.5.3
astropy==2.0.2
azure==3.0.0
azure-batch==4.1.3
azure-common==1.1.11
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.3
azure-datalake-store==0.0.19
azure-eventgrid==0.1.0
azure-graphrbac==0.40.0
azure-keyvault==0.3.7
azure-mgmt==2.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==0.2.0
azure-mgmt-billing==0.1.0
azure-mgmt-cdn==2.0.0
azure-mgmt-cognitiveservices==2.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==3.0.1
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==0.3.1
azure-mgmt-containerregistry==1.0.1
azure-mgmt-containerservice==3.0.1
azure-mgmt-cosmosdb==0.3.1
azure-mgmt-datafactory==0.4.0
azure-mgmt-datalake-analytics==0.3.0
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.3.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==1.2.0
azure-mgmt-eventgrid==0.4.0
azure-mgmt-eventhub==1.2.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iothub==0.4.0
azure-mgmt-iothubprovisioningservices==0.1.0
azure-mgmt-keyvault==0.40.0
azure-mgmt-loganalytics==0.1.0
azure-mgmt-logic==2.1.0
azure-mgmt-machinelearningcompute==0.4.0
azure-mgmt-managementpartner==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==0.2.0
azure-mgmt-monitor==0.4.0
azure-mgmt-msi==0.1.0
azure-mgmt-network==1.7.1
azure-mgmt-notificationhubs==1.0.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-powerbiembedded==1.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-recoveryservices==0.2.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.1.0
azure-mgmt-resource==1.2.2
azure-mgmt-scheduler==1.1.3
azure-mgmt-search==1.0.0
azure-mgmt-servermanager==1.2.0
azure-mgmt-servicebus==0.4.0
azure-mgmt-servicefabric==0.1.0
azure-mgmt-sql==0.8.6
azure-mgmt-storage==1.5.0
azure-mgmt-subscription==0.1.0
azure-mgmt-trafficmanager==0.40.0
azure-mgmt-web==0.34.1
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==6.1.2.9
azure-servicemanagement-legacy==0.20.6
azure-storage-blob==1.1.0
azure-storage-common==1.1.0
azure-storage-file==1.1.0
azure-storage-nspkg==3.0.0
azure-storage-queue==1.1.0
Babel==2.5.0
backcall==0.1.0
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==1.5.0
bokeh==0.12.10
boto==2.48.0
boto3==1.7.48
botocore==1.10.48
Bottleneck==1.2.1
bz2file==0.98
cachetools==2.1.0
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
click==6.7
click-log==0.1.8
cloudpickle==0.5.2
cloudstorage==0.5
clusterone==0.13.4
clyent==1.2.2
cmocean==1.2
colorama==0.3.9
colorspacious==1.1.2
conda==4.4.6
conda-build==3.0.27
conda-verify==2.0.0
configparser==3.5.0
contextlib2==0.5.5
coreapi==2.3.3
coreapi-cli==1.0.9
coreschema==0.0.4
cryptography==2.0.3
cycler==0.10.0
Cython==0.28.5
cytoolz==0.8.2
dask==0.15.3
datashape==0.5.4
decorator==4.3.0
deprecation==2.0.2
dicom==0.9.9.post1
dill==0.2.7.1
distributed==1.19.1
docutils==0.14
dogpile.cache==0.6.5
dominate==2.3.1
entrypoints==0.2.3
enum34==1.1.6
et-xmlfile==1.0.1
fastcache==1.0.2
fasttext==0.8.22
filelock==2.0.12
Flask==0.12.2
Flask-Cors==3.0.3
funcsigs==1.0.2
future==0.16.0
futures==3.1.1
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
gast==0.2.0
gcloud==0.18.3
gensim==3.4.0
gevent==1.2.2
gitdb2==2.0.4
GitPython==2.1.11
glob2==0.5
gmpy2==2.0.8
google-api-core==0.1.4
google-api-python-client==1.6.7
google-auth==1.4.1
google-cloud==0.32.0
google-cloud-bigquery==0.28.0
google-cloud-bigquery-datatransfer==0.1.1
google-cloud-bigtable==0.28.1
google-cloud-container==0.1.1
google-cloud-core==0.28.1
google-cloud-datastore==1.4.0
google-cloud-dns==0.28.0
google-cloud-error-reporting==0.28.0
google-cloud-firestore==0.28.0
google-cloud-language==1.0.2
google-cloud-logging==1.4.0
google-cloud-monitoring==0.28.1
google-cloud-pubsub==0.30.1
google-cloud-resource-manager==0.28.1
google-cloud-runtimeconfig==0.28.1
google-cloud-spanner==0.29.0
google-cloud-speech==0.30.0
google-cloud-storage==1.6.0
google-cloud-trace==0.17.0
google-cloud-translate==1.3.1
google-cloud-videointelligence==1.0.1
google-cloud-vision==0.29.0
google-gax==0.15.16
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
greenlet==0.4.12
grpc-google-iam-v1==0.11.4
grpcio==1.12.0
gym==0.10.4
h5py==2.8.0
heapdict==1.0.0
html5lib==0.9999999
httplib2==0.11.3
idna==2.6
imageio==2.2.0
imagesize==0.7.1
imgaug==0.2.6
inflection==0.3.1
ipdb==0.11
ipykernel==4.7.0
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.0.0
iso8601==0.1.12
isodate==0.6.0
isort==4.2.15
itsdangerous==0.24
itypes==1.1.0
jdcal==1.3
jedi==0.12.1
Jinja2==2.9.6
jmespath==0.9.3
jsonpatch==1.23
jsonpointer==2.0
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.3.0
jupyterlab==0.27.0
jupyterlab-launcher==0.4.0
Keras==2.2.2
Keras-Applications==1.0.4
Keras-Preprocessing==1.0.2
keyring==12.2.1
keystoneauth1==3.7.0
lazy-object-proxy==1.3.1
LEPL==5.1.3
lime==0.1.1.29
lineedit==0.1.1
llvmlite==0.20.0
locket==0.2.0
lxml==4.1.0
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.1.0
mccabe==0.6.1
mistune==0.7.4
mkl-fft==1.0.2
mkl-random==1.0.1
mock==2.0.0
mpld3==0.3.1.dev1
mpmath==0.19
msgpack-python==0.4.8
msrest==0.4.29
msrestazure==0.4.31
multipledispatch==0.4.9
munch==2.3.2
navigator-updater==0.1.0
nb-conda-kernels==2.1.0
nbconvert==5.3.1
nbformat==4.4.0
netifaces==0.10.7
networkx==2.0
nibabel==2.2.1
nipype==1.0.2
nltk==3.2.4
nose==1.3.7
notebook==5.0.0
numba==0.35.0+6.gaa35fb1
numexpr==2.6.2
numpy==1.15.0
numpydoc==0.7.0
oauth2client==4.1.2
oauthlib==2.1.0
odo==0.5.1
olefile==0.44
openpyxl==2.4.8
openstacksdk==0.13.0
os-service-types==1.2.0
packaging==16.8
pandas==0.20.3
pandocfilters==1.4.2
parso==0.3.1
partd==0.3.8
path.py==10.3.1
pathlib2==2.3.0
patsy==0.4.1
pbr==4.0.1
pep8==1.7.0
pexpect==4.6.0
pickleshare==0.7.4
Pillow==4.2.1
pkginfo==1.4.1
ply==3.8
prompt-toolkit==1.0.15
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
protobuf==3.5.2.post1
prov==1.5.0
psutil==5.4.0
ptyprocess==0.6.0
py==1.4.34
pyaml==17.12.1
pyasn1==0.4.3
pyasn1-modules==0.2.1
pybind11==2.2.3
-e git+https://github.com/DSLituiev/cocoapi@eed13d3f9cfcc8d556a1861d1587d37059c0e712#egg=pycocotools&subdirectory=PythonAPI
pycodestyle==2.3.1
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pydicom==1.1.0
pydot==1.2.4
pydotplus==2.0.2
pyflakes==1.6.0
pyglet==1.3.1
Pygments==2.2.0
PyJWT==1.6.4
pylint==1.7.4
pymongo==3.6.0
pyodbc==4.0.17
pyOpenSSL==17.2.0
pyparsing==2.2.0
PyQt5==5.9.2
PySocks==1.6.7
pytest==3.2.1
python-dateutil==2.6.1
python-magic==0.4.15
pytz==2017.2
PyWavelets==0.5.2
PyYAML==3.13
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
rackspaceauth==0.2.0
rackspacesdk==0.7.5
rapi==0.1.1
raven==6.9.0
rdflib==4.2.2
requests==2.18.4
requests-oauthlib==0.8.0
requestsexceptions==1.4.0
rfc6266-parser==0.0.5.post2
-e git+git@github.com:DSLituiev/rle.git@6c3934f6baf2329faa1b3cebc89de8341a85ae1b#egg=RLE
rope==0.10.5
rpy2==2.9.4
rsa==3.4.2
rtichoke==0.2.8
ruamel-yaml==0.11.14
s3transfer==0.1.13
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.1.0
seaborn==0.8
simplegeneric==0.8.1
simplejson==3.13.2
singledispatch==3.4.0.3
sip==4.19.6
six==1.11.0
smart-open==1.6.0
smmap2==2.0.4
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.7
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.8
SQLAlchemy==1.1.13
statsmodels==0.8.0
stevedore==1.28.0
sympy==1.1.1
tables==3.4.2
tblib==1.3.2
tensorboard==1.8.0
tensorflow==1.8.0
tensorflow-tensorboard==0.4.0rc3
termcolor==1.1.0
terminado==0.6
terminaltables==3.1.0
testpath==0.3.1
toolz==0.8.2
torch==0.4.1
torchfile==0.1.0
torchvision==0.2.0
tornado==4.5.2
traitlets==4.3.2
traits==4.6.0
typing==3.6.4
tzlocal==1.5.1
uritemplate==3.0.0
urllib3==1.22
virtualenv==15.2.0
-e git+https://github.com/raghakot/keras-vis@40b27dfa3ecb84cdde5ec6b44251923c3266cc40#egg=vis
viscm==0.7
visdom==0.1.8.3
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.47.0
Werkzeug==0.14.1
widgetsnbextension==3.0.2
wrapt==1.10.11
xattr==0.9.3
xlrd==1.1.0
zict==0.1.3

</p>
</details>

**Comment by chummels** [comment]
I had this same problem, but if you just clone directly from this repo, it works OK.  I guess the PyPI version is old.  This is described in Issue #36 .

**Comment by stefanv** [comment]
Should be fixed by the latest release.  Please re-open if not.
