### ISSUE TITLE
QT4Agg deprecation

### ISSUE THREAD

**Issue by MBravoS** [matplotlib/viscm#55]
Version 3.3 of matplotlib added a deprecation warning for QT4Agg, which seems planned to be deprecated in 3.5. If I'm understanding correctly how things work, that would mean from 3.5 that this call in gui.py:
`from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas4`
will throw an error. Changing this:
```
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas4
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas5

def FigureCanvas(fig):
    try:
        return FigureCanvas5(fig)
    except Exception:
        return FigureCanvas4(fig)
```
to this:
```
try:
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
except Exception: 
    from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
```
should do the trick. I'm happy to make a pull request with that change if needed/desired.

**Comment by jkunimune** [comment]
It's worth noting that this does now throw an error.  I guess viscm isn't actively supported anymore, but would it be possible to just pull #57, @tacaswell or @stefanv or whoever has the power?

**Comment by stefanv** [comment]
viscm should be actively supported! Let us know of critical issues.

**Comment by tacaswell** [comment]
@stefanv We need to cut a release with #57 merged.
