### ISSUE TITLE
Use compound cubic Bezier path

### ISSUE THREAD

**Issue by scott-maddox** [matplotlib/viscm#6]
Currently, the colormap path is defined by an N-order Bezier path, where N is equal to the number of control points minus 1. Controlling this becomes fairly unintuitive when N > 3. Control could be made more intuitive if the colormap path were composed of a series of cubic (3rd-order) Bezier paths. This is the approach taken by Photoshop, Inkscape, etc.

Unfortunately, this would take a significant amount of modifications to accomplish, and I do not currently have the time to take it on. It would make defining complex paths much easier, though.

**Comment by amueller** [comment]
+1

**Comment by njsmith** [comment]
Current master uses something more-or-less equivalent to this.
