### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by tlambert03** [matplotlib/viscm#61]
Howdie 👋

I just came by to start fixing the qt4 bug in the latest release, but then found it had already been fixed back in June by https://github.com/matplotlib/viscm/pull/57

any chance we could get a release on pypi?

**Comment by MattF-NSIDC** [comment]
Don't like to bump threads, but I recently tried to use `viscm` after getting a new laptop. It used to be usable after installing with conda, but not anymore (`ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'`, see #55). I'd be willing to help fix up the conda-forge feedstock, but the first step is getting this released onto PyPI.

@stefanv @njsmith could you help out with this?

**Comment by njsmith** [comment]
I don't think we have a ton of bandwidth for viscm these days... anyone
want to take over maintaining it?

**Comment by MattF-NSIDC** [comment]
I would absolutely be willing to become a maintainer of this project, but I need to work out whether I can be funded to do it during work time.

**Comment by mfisher87** [comment]
No go on getting time allocated at work for this, but I'm willing to contribute to maintenance on my personal time. This is @MattF-NSIDC 's personal account (I regret having two accounts right now :laughing:).

Would you be able to provide onboarding support as I get started? I don't see any documentation or automation for releasing, so I'd like to start with automating the release process with Actions or Travis if you prefer, but I haven't used Travis much :)

**Comment by stefanv** [comment]
I'd be happy to assist with that, @mfisher87. Thanks for your willingness to help out!

**Comment by mfisher87** [comment]
Great, thanks @stefanv ! Do you have a preferred communication method for onboarding and discussing PyPI auth? Happy to join a Slack instance or Zoom or whatever works for you. Timing-wise, best for me is the weekend or weekday evenings, but have some flexibility. I live in UTC-6 and typically work until 6PM.

**Comment by stefanv** [comment]
Either the Scientific Python discord (see link at bottom of scientific-python.org), or via email should be fine.

**Comment by mfisher87** [comment]
I've been working on getting another open-source project packaged for release for the last couple of weekends, but should be free to start looking at this this weekend. I'll hopefully see you in Discord soon :)

**Comment by mfisher87** [comment]
Update: Packaging is updated to modern conventions, added some code quality checks to help prevent me from breaking stuff going forward, and I think all barriers to actually putting this on PyPI are now removed. I'll probably not have time to actually release before this weekend, but maybe will have some time to test and merge some PRs during the week.

**Comment by stefanv** [comment]
Thanks very much for all your work @mfisher87!

**Comment by MattF-NSIDC** [comment]
Thanks for your support :heart:

**Comment by kthyng** [comment]
Thank you for doing this @MattF-NSIDC !!

**Comment by mfisher87** [comment]
Happy to! Thank _you_ for `cmocean`, they're my favorite colormaps! We're using them in QGreenland, and I'll be running a workshop for researchers with a colleague starting tomorrow, and we have a slide where we recommend them ;)

**Comment by kthyng** [comment]
@mfisher87 Awesome! Thank you! Hope your workshop goes well.

**Comment by mfisher87** [comment]
Thank you :) So far, going great, and lots of fun. We had a module on FAIR & CARE principles today and asked our attendees to post some thoughts [on GH Discussions](https://github.com/orgs/qgreenland-workshop-2023-researcher/discussions/categories/fair-care) and they shared so much interesting stuff! I'll be presenting our module on symbology tomorrow :)

**Comment by mfisher87** [comment]
v0.10 is out (on PyPI. conda-forge coming soon)! Thanks to all for your patience :heart:

**Comment by mfisher87** [comment]
Now on `conda-forge`!
